allow to exit on incorrect credentials

diff --git a/bin/setup-new-repo b/bin/setup-new-repo
--- a/bin/setup-new-repo
+++ b/bin/setup-new-repo
@@ -43,11 +43,18 @@ function share_key {
 }
 
 function main {
+    retry=5
 
     bw logout
 
     until BW_SESSION=$(bw login --raw $BITWARDEN_EMAIL $BITWARDEN_PASSWORD)
     do
+        retry=$retry-1
+        if [[ $retry -eq 0 ]] ; then
+            echo "Unable to log in your Bitwarden account. Please check your credential."
+            exit 3
+        fi
+        sleep 3
         echo "Please try again ..."
     done
 
